name: Update README with Latest Dev.to Posts

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every hour
  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install rss-parser

      - name: Run Script
        run: node .github/scripts/update-readme.js

      - name: Commit Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README with latest blog posts" -a || echo "No changes to commit"
          git push
